[platformio]
src_dir = .
include_dir = .

[env:base]
platform = ststm32
board = nucleo_f446ze
upload_protocol = stlink
monitor_speed = 115200

board_build.ldscript = ./STM32F446ZETx_FLASH.ld

build_flags =

    -Wl,-Map,./.pio/build/base/output_base.map

    -DUSE_HAL_DRIVER
    -DSCNu8=\"hhu\"
    -DSCNi8=\"hhi\"
    -D_XOPEN_SOURCE
    -D HSE_VALUE=16000000 ; define HSE value for clock configuration (I don't know if this is right but looking at the ioc this seems to be the value for the external crystal on the board)

    -ICore/Inc
    -ICore/Inc/common
    -ICore/Inc/bms
    -ICore/Inc/bms/errors
    -ICore/Inc/bms/drivers
    -ICore/Inc/bms/cooling
    -ICore/Inc/bms/timebase
    -ICore/Lib
    -ICore/Lib/micro-libs/bms-monitor/inc
    -ICore/Lib/micro-libs/ring-buffer/inc
    -ICore/Lib/micro-libs/errorlib/inc
    -ICore/Lib/micro-libs/blinky/inc
    -ICore/Lib/micro-libs/min-heap/inc
    -ICore/Lib/micro-libs/timer-utils
    -ICore/Lib/can/lib/bms
    -ICore/Lib/can/lib
    -ICore/Lib/can/lib/primary
    -IDrivers/CMSIS/Device/ST/STM32F4xx/Include
    -IDrivers/CMSIS/Include
    -IDrivers/STM32F4xx_HAL_Driver/Inc
    ;-IDrivers/STM32F4xx_HAL_Driver/Inc/Legacy

build_src_filter =
    +<Core/Src/**>
    +<Core/Lib/**>

    +<Drivers/STM32F4xx_HAL_Driver/Src/**>
    ; exclude test/example folders
    -<**/micro-libs/**>
    +<**/micro-libs/bms-monitor/**>
    +<**/micro-libs/ring-buffer/src>
    +<**/micro-libs/errorlib/src>
    +<**/micro-libs/blinky/src>
    +<**/micro-libs/min-heap/src>
    +<**/micro-libs/timer-utils>
    -<**/micro-libs/**/tests/**>
    -<**/micro-libs/**/test/**>
    -<**/micro-libs/**/example/**>
    -<**/micro-libs/**/examples/**>
    -<Drivers/STM32F4xx_HAL_Driver/Src/**/*_template.c>

    ; exclude CAN cpp duplicates
    -<**/*_utils.cpp>

    +<./startup_stm32f446xx.s>


[env:tests]
platform = native
test_framework = unity
test_build_src = true
build_flags =

    -DUSE_HAL_DRIVER
    -DSCNu8=\"hhu\"
    -DSCNi8=\"hhi\"
    -D_XOPEN_SOURCE
    -D HSE_VALUE=16000000 ; define HSE value for clock configuration (I don't know if this is right but looking at the ioc this seems to be the value for the external crystal on the board)
    -D_STATIC=

    -ICore/Inc
    -ICore/Inc/common
    -ICore/Inc/bms
    -ICore/Inc/bms/errors
    -ICore/Inc/bms/drivers
    -ICore/Inc/bms/cooling
    -ICore/Inc/bms/timebase
    -ICore/Lib
    -ICore/Lib/micro-libs/bms-monitor/inc
    -ICore/Lib/micro-libs/ring-buffer/inc
    -ICore/Lib/micro-libs/errorlib/inc
    -ICore/Lib/micro-libs/blinky/inc
    -ICore/Lib/micro-libs/min-heap/inc
    -ICore/Lib/micro-libs/timer-utils
    -ICore/Lib/can/lib/bms
    -ICore/Lib/can/lib
    -ICore/Lib/can/lib/primary
    -lm

build_src_filter =
    +<Core/Src/bms/**>
    +<Core/Lib/bms/**>

    +<Core/Lib/can/lib/**>

    ; exclude test/example folders
    -<**/micro-libs/**>
    +<**/micro-libs/bms-monitor/**>
    +<**/micro-libs/ring-buffer/src>
    +<**/micro-libs/errorlib/src>
    +<**/micro-libs/blinky/src>
    +<**/micro-libs/min-heap/src>
    -<**/micro-libs/**/tests/**>
    -<**/micro-libs/**/test/**>
    -<**/micro-libs/**/example/**>
    -<**/micro-libs/**/examples/**>

    ; exclude CAN cpp duplicates
    -<**/*_utils.cpp>

[env:balancing_tests]
extends = env:tests
build_flags =
    ${env:tests.build_flags}
    -DBALANCING_TESTS=1

[env:can_comm_tests]
extends = env:tests
build_flags =
    ${env:tests.build_flags}
    -DCAN_COMM_TESTS=1

; yet to be implemented

[env:current_tests]
extends = env:tests
;debug_test = *
build_flags =
    ${env:tests.build_flags}
    -DCURRENT_TESTS=1

[env:display_tests]
extends = env:tests
build_flags =
    ${env:tests.build_flags}
    -DDISPLAY_TESTS=1

[env:feedback_tests]
extends = env:tests
;debug_test = *
build_flags =
    ${env:tests.build_flags}
    -DFEEDBACK_TESTS=1

[env:identity_tests]
extends = env:tests
;debug_test = *
build_flags =
    ${env:tests.build_flags}
    -DIDENTITY_TESTS=1

[env:imd_tests]
extends = env:tests
build_flags =
    ${env:tests.build_flags}
    -DIMD_TESTS=1

[env:internal_voltage_tests]
extends = env:tests
build_flags =
    ${env:tests.build_flags}
    -DINTERNAL_VOLTAGE_TESTS=1

[env:led_tests]
extends = env:tests
build_flags =
    ${env:tests.build_flags}
    -DLED_TESTS=1

[env:pcu_tests]
extends = env:tests
build_flags =
    ${env:tests.build_flags}
    -DPCU_TESTS=1

[env:temp_tests]
extends = env:tests
build_flags =
    ${env:tests.build_flags}
    -DTEMP_TESTS=1

[env:volt_tests]
extends = env:tests
build_flags =
    ${env:tests.build_flags}
    -DVOLT_TESTS=1

[env:tasks_tests]
extends = env:tests
build_flags =
    ${env:tests.build_flags}
    -DTASKS_TESTS=1


[env:timebase_tests]
extends = env:tests
debug_test = *
build_flags =
    ${env:tests.build_flags}
    -DTIMEBASE_TESTS=1
