[platformio]
src_dir = .
include_dir = .
test_dir = test
default_envs = release

[env]
lib_deps =
    https://github.com/eagletrt/libeagletrt-sw.git#v0.1.0

[env:release]
platform = ststm32
upload_protocol = stlink
platform_packages =
  toolchain-gccarmnoneeabi@=1.140201.0
monitor_speed = 115200
extra_scripts = pre:scripts/build_script.py

board = nucleo_f446ze
board_build.ldscript = ./STM32F446ZETx_FLASH.ld

build_flags =

    -std=gnu23

    -Wl,-Map,./.pio/build/release/output_release.map

    -DUSE_HAL_DRIVER
    -DSCNu8=\"hhu\"
    -DSCNi8=\"hhi\"
    -D_XOPEN_SOURCE
    -D HSE_VALUE=16000000 ; define HSE value for clock configuration (I don't know if this is right but looking at the ioc this seems to be the value for the external crystal on the board)

    -ICore/Inc
    -ICore/Inc/common
    -ICore/Inc/bms
    -ICore/Inc/bms/errors
    -ICore/Inc/bms/drivers
    -ICore/Inc/bms/cooling
    -ICore/Inc/bms/timebase
    -ICore/Inc/bms/current
    -ICore/Lib
    -ICore/Lib/micro-libs/bms-monitor/inc
    -ICore/Lib/micro-libs/ring-buffer/inc
    -ICore/Lib/micro-libs/errorlib/inc
    -ICore/Lib/micro-libs/blinky/inc
    -ICore/Lib/micro-libs/min-heap/inc
    -ICore/Lib/micro-libs/timer-utils
    -ICore/Lib/can/lib/bms
    -ICore/Lib/can/lib
    -ICore/Lib/can/lib/primary
    -IDrivers/CMSIS/Device/ST/STM32F4xx/Include
    -IDrivers/CMSIS/Include
    -IDrivers/STM32F4xx_HAL_Driver/Inc

build_src_filter =
    +<Core/Src/**>
    +<Core/Lib/**>

    +<Drivers/STM32F4xx_HAL_Driver/Src/**>
    -<**/micro-libs/**>
    +<**/micro-libs/bms-monitor/**>
    +<**/micro-libs/ring-buffer/src>
    +<**/micro-libs/errorlib/src>
    +<**/micro-libs/blinky/src>
    +<**/micro-libs/min-heap/src>
    +<**/micro-libs/timer-utils>
    -<**/micro-libs/**/tests/**>
    -<**/micro-libs/**/test/**>
    -<**/micro-libs/**/example/**>
    -<**/micro-libs/**/examples/**>
    -<Drivers/STM32F4xx_HAL_Driver/Src/**/*_template.c>

    -<**/*_utils.cpp>

    +<./startup_stm32f446xx.s>

check_tool = clangtidy
check_flags =
    clangtidy: --checks=-*,cert-*,clang-analyzer-*,bugprone-*,performance-*,readability-*,-bugprone-easily-swappable-parameters
    clangtidy: --warnings-as-errors=clang-analyzer-*,bugprone-*
    clangtidy: --header-filter=^.*Core/(Inc|Src)/.+/[^/]+\.(c|h)$
    clangtidy: --system-headers=false
check_src_filters =
    -<**>
    +<Core/Src/bms>
    +<Core/Inc/bms>



[env:tests]
platform = native
test_framework = unity
test_build_src = true

build_flags =

    -std=gnu23

    -DEAGLETRT_STATIC=
    -DEAGLETRT_STATIC_INLINE=

    -DUSE_HAL_DRIVER
    -DSCNu8=\"hhu\"
    -DSCNi8=\"hhi\"
    -D_XOPEN_SOURCE
    -D HSE_VALUE=16000000 ; define HSE value for clock configuration (I don't know if this is right but looking at the ioc this seems to be the value for the external crystal on the board)
    -D_STATIC=


    ; Kept for debugging purposes
    -DBALANCING_TESTS=1
    -DCAN_COMM_TESTS=1
    -DCURRENT_TESTS=1
    -DDISPLAY_TESTS=1
    -DFEEDBACK_TESTS=1
    -DIDENTITY_TESTS=1
    -DIMD_TESTS=1
    -DINTERNAL_VOLTAGE_TESTS=1
    -DLED_TESTS=1
    -DPCU_TESTS=1
    -DTEMP_TESTS=1
    -DVOLT_TESTS=1
    -DTASKS_TESTS=1
    -DTIMEBASE_TESTS=1

    -Itest/include

    -ICore/Inc
    -ICore/Inc/common
    -ICore/Inc/bms
    -ICore/Inc/bms/errors
    -ICore/Inc/bms/drivers
    -ICore/Inc/bms/cooling
    -ICore/Inc/bms/timebase
    -ICore/Inc/bms/current
    -ICore/Lib
    -ICore/Lib/micro-libs/bms-monitor/inc
    -ICore/Lib/micro-libs/ring-buffer/inc
    -ICore/Lib/micro-libs/errorlib/inc
    -ICore/Lib/micro-libs/blinky/inc
    -ICore/Lib/micro-libs/min-heap/inc
    -ICore/Lib/micro-libs/timer-utils
    -ICore/Lib/can/lib/bms
    -ICore/Lib/can/lib
    -ICore/Lib/can/lib/primary
    -lm

build_src_filter =
    +<Core/Src/bms/**>
    +<Core/Lib/bms/**>

    +<Core/Lib/can/lib/**>

    ; exclude test/example folders
    -<**/micro-libs/**>
    +<**/micro-libs/bms-monitor/**>
    +<**/micro-libs/ring-buffer/src>
    +<**/micro-libs/errorlib/src>
    +<**/micro-libs/blinky/src>
    +<**/micro-libs/min-heap/src>
    -<**/micro-libs/**/tests/**>
    -<**/micro-libs/**/test/**>
    -<**/micro-libs/**/example/**>
    -<**/micro-libs/**/examples/**>

    ; exclude CAN cpp duplicates
    -<**/*_utils.cpp>
