[platformio]
src_dir = .
include_dir = .

[env:bootloader]
platform = ststm32
board = genericSTM32F407VGT6
upload_protocol = stlink
monitor_speed = 115200
board_build.ldscript = ./hv-bms-cellboard-bootloader-sw/STM32F446ZETx_FLASH.ld


build_flags =

    -Wl,-Map,./.pio/build/bootloader/output_bootloader.map

    -DUSE_HAL_DRIVER
    -DUSE_FULL_LL_DRIVER
    -Ihv-bms-cellboard-bootloader-sw/Core/Inc
    -Ihv-bms-cellboard-bootloader-sw/Core/Inc/libopenblt

build_src_filter =
    +<hv-bms-cellboard-bootloader-sw/Core/Src/**>
    +<hv-bms-cellboard-bootloader-sw/Drivers/STM32F4xx_HAL_Driver/Src/**>
    +<hv-bms-cellboard-bootloader-sw/startup_stm32f446xx.s>


[env:base]
platform = ststm32
board = nucleo_f446ze
upload_protocol = stlink
monitor_speed = 115200
framework = stm32cube

board_build.ldscript = ./STM32F446ZETx_FLASH.ld

build_flags =

    -Wl,-Map,./.pio/build/base/output_base.map

    -DUSE_HAL_DRIVER
    -DSCNu8=\"hhu\"
    -DSCNi8=\"hhi\"
    -D_XOPEN_SOURCE
    -D HSE_VALUE=16000000 ; define HSE value for clock configuration (I don't know if this is right but looking at the ioc this seems to be the value for the external crystal on the board)

    -ICore/Inc
    -ICore/Inc/common
    -ICore/Inc/bms
    -ICore/Inc/bms/errors
    -ICore/Inc/bms/drivers
    -ICore/Inc/bms/cooling
    -ICore/Inc/bms/timebase
    -ICore/Lib
    -ICore/Lib/micro-libs/bms-monitor/inc
    -ICore/Lib/micro-libs/ring-buffer/inc
    -ICore/Lib/micro-libs/errorlib/inc
    -ICore/Lib/micro-libs/blinky/inc
    -ICore/Lib/micro-libs/min-heap/inc
    -ICore/Lib/micro-libs/timer-utils
    -ICore/Lib/can/lib/bms
    -ICore/Lib/can/lib
    -ICore/Lib/can/lib/primary

build_src_filter =
    +<Core/Src/**>
    +<Core/Lib/**>
    ; exclude test/example folders
    -<**/micro-libs/**>

    +<**/micro-libs/bms-monitor/**>
    +<**/micro-libs/ring-buffer/src>
    +<**/micro-libs/errorlib/src>
    +<**/micro-libs/blinky/src>
    +<**/micro-libs/min-heap/src>
    +<**/micro-libs/timer-utils>
    -<**/micro-libs/**/tests/**>
    -<**/micro-libs/**/test/**>
    -<**/micro-libs/**/example/**>
    -<**/micro-libs/**/examples/**>

    ; exclude CAN cpp duplicates
    -<**/*_utils.cpp>

    +<./startup_stm32f446xx.s>
