/*******************************************************************************
 * Critical error handler library generator
 * Generated by error_gen ruby gem, for more information see:
 * https://github.com/eagletrt/micro-utils/tree/master/error-handler-generator
 *
 * Error_gen version 1.6.1
 * Generation date: 2024-07-12 22:56:47 +0200
 * Generated from: errors.json
 * With prefix: error_handler
 * The error handler contains:
 *     - 2 error groups
 *     - 2 total error instances
 ******************************************************************************/

#include "error-handler.h"

#include <string.h>

#include "ring-buffer.h"
#include "min-heap.h"

// Ring buffer maximum number of elements
#define ERROR_HANDLER_ERROR_BUFFER_SIZE 16

/**
 * @brief Error data type definition needed to manage the errors
 *
 * @param group The group to which the error belongs
 * @param instance The instance of the error
 * @param timestamp The current time (in ms)
 * @param op A pointer to the operation that needs to be executed
 */
typedef struct _ErrorHandlerErrorData {
    ErrorHandlerErrorGroup group;
    ErrorHandlerErrorInstance instance;
    uint32_t timestamp;
    void (* op)(struct _ErrorHandlerErrorData);
} ErrorHandlerErrorData;

/** @brief Total number of instances for each group */
static const uint16_t instances[] = {
    [ERROR_HANDLER_ERROR_GROUP_POST] = 1,
    [ERROR_HANDLER_ERROR_GROUP_OVER_CURRENT] = 1
};
/** @brief Error timeout for each group */
static const uint16_t timeouts[] = {
    [ERROR_HANDLER_ERROR_GROUP_POST] = 0,
    [ERROR_HANDLER_ERROR_GROUP_OVER_CURRENT] = 20
};

/** @brief List of errors where the data is stored */
static ErrorHandlerError error_handler_error_post_instances[1];
static ErrorHandlerError error_handler_error_over_current_instances[1];
static ErrorHandlerError * errors[] = {
    [ERROR_HANDLER_ERROR_GROUP_POST] = error_handler_error_post_instances,
    [ERROR_HANDLER_ERROR_GROUP_OVER_CURRENT] = error_handler_error_over_current_instances
};

/** @brief Function declaration needed for the min heap */
int8_t _error_handler_error_compare(void * a, void * b);

bool routine_lock = false;
RingBuffer(ErrorHandlerErrorData, ERROR_HANDLER_ERROR_BUFFER_SIZE) err_buf;
RingBuffer(ErrorHandlerError *, ERROR_HANDLER_ERROR_INSTANCE_COUNT) expired_errors = ring_buffer_new(ErrorHandlerError *, ERROR_HANDLER_ERROR_INSTANCE_COUNT, NULL, NULL);
MinHeap(ErrorHandlerError *, ERROR_HANDLER_ERROR_INSTANCE_COUNT) running_errors = min_heap_new(ErrorHandlerError *, ERROR_HANDLER_ERROR_INSTANCE_COUNT, _error_handler_error_compare);

/** @brief Fast lookup for groups that are running or expired */
uint16_t running_groups[ERROR_HANDLER_ERROR_GROUP_COUNT];
uint16_t expired_groups[ERROR_HANDLER_ERROR_GROUP_COUNT];

/**
 * @brief Compare two errors based on the time when they were set
 * and their timeouts
 *
 * @param t1 The timestamp of the first error
 * @param dt1 The timeout of the first error
 * @param t2 The timestamp of the second error
 * @param dt2 The timeout of the second error
 * @return int32_t The difference between the two expire times
 */
int8_t _error_handler_error_compare(void * a, void * b) {
    ErrorHandlerError * e1 = *(ErrorHandlerError **)a;
    ErrorHandlerError * e2 = *(ErrorHandlerError **)b;
    int32_t t1 = e1->timestamp + timeouts[e1->group];
    int32_t t2 = e2->timestamp + timeouts[e2->group];
    return t1 < t2 ? -1 : (t1 == t2 ? 0 : 1);
}

/**
 * @brief Set the error if possible and update the timer if necessary
 *
 * @param data The data of the error to set
 */
void _error_handler_error_set(ErrorHandlerErrorData data) {
    // Get error
    ErrorHandlerError * err = &errors[data.group][data.instance];
    if (err->is_running || err->is_expired)
        return;

    // Update error info
    err->is_running = true;
    err->timestamp = data.timestamp;
    ++running_groups[data.group];

    // Add error to the running list of errors and
    // update timer if the error is the first to expire
    if (min_heap_insert(&running_errors, &err) != MIN_HEAP_OK)
        return;
    ErrorHandlerError ** top = (ErrorHandlerError **)min_heap_peek(&running_errors);
    if (top != NULL && *top == err)
        error_handler_error_update_timer_callback(err->timestamp, timeouts[err->group]);
}

/**
 * @brief Reset the error if possible and update the timer if necessary
 *
 * @param data The data of the error to reset
 */
void _error_handler_error_reset(ErrorHandlerErrorData data) {
    // Get error
    ErrorHandlerError * err = &errors[data.group][data.instance];
    if (!err->is_running || err->is_expired)
        return;

    // Update error info
    err->is_running = false;
    --running_groups[data.group];

    // Get the current first element
    ErrorHandlerError * top = NULL;
    if (min_heap_top(&running_errors, &top) != MIN_HEAP_OK)
        return;

    if (top == err) {
        // If the removed error is the first in the heap
        // remove it and update (or stop) the timer
        if (min_heap_remove(&running_errors, 0, NULL) != MIN_HEAP_OK)
            return;

        if (min_heap_is_empty(&running_errors))
            error_handler_error_stop_timer_callback();
        else if (min_heap_top(&running_errors, &top) == MIN_HEAP_OK)
            error_handler_error_update_timer_callback(top->timestamp, timeouts[top->group]);
    }
    else {
        // Find and remove the error
        signed_size_t i = min_heap_find(&running_errors, &err);
        if (i < 0) return;
        min_heap_remove(&running_errors, i, NULL);
    }
}

/**
 * @brief Expire the error
 *
 * @param data The data of the error to expire
 */
void _error_handler_error_expire(ErrorHandlerErrorData data) {
    // Get error
    ErrorHandlerError * top = NULL;
    if (min_heap_top(&running_errors, &top) != MIN_HEAP_OK)
        return;

    if (!top->is_running || top->is_expired)
        return;

    ErrorHandlerError * prev = top;
    do {
        // Update error info
        top->is_running = false;
        top->is_expired = true;
        --running_groups[data.group];
        ++expired_groups[data.group];

        // Add error to the list of expired errors
        if (ring_buffer_push_back(&expired_errors, &top) != RING_BUFFER_OK)
            break;

        // Get next error and remove the previous
        if (min_heap_remove(&running_errors, 0, NULL) != MIN_HEAP_OK)
            break;

        // Stop the timer if there are no more errors
        if (min_heap_is_empty(&running_errors)) {
            error_handler_error_stop_timer_callback();
            return;
        }

        // Get next errors
        if (min_heap_top(&running_errors, &top) != MIN_HEAP_OK)
            break;
    } while(_error_handler_error_compare(&top, &prev) <= 0);

    // Update the timer
    if (top != NULL)
        error_handler_error_update_timer_callback(top->timestamp, timeouts[top->group]);
}
/**
 * @brief Expire the error immediately without waiting for the timer
 *
 * @param data The data of the error to expire
 */
void _error_handler_error_expire_immediate(ErrorHandlerErrorData data) {
    // Get error
    ErrorHandlerError * err = &errors[data.group][data.instance];
    if (err->is_expired)
        return;

    // Update error info
    err->is_expired = true;
    ++expired_groups[data.group];
    if (err->is_running) {
        err->is_running = false;
        --running_groups[data.group];
    }

    // Add error to the list of expired errors
    if (ring_buffer_push_back(&expired_errors, &err) != RING_BUFFER_OK)
        return;

    // Remove the error from the list of running errors
    signed_size_t index = min_heap_find(&running_errors, &err);
    if (index < 0)
        return;
    if (min_heap_remove(&running_errors, index, NULL) != MIN_HEAP_OK)
        return;

    // Stop the timer if there are no more errors
    if (min_heap_is_empty(&running_errors)) {
        error_handler_error_stop_timer_callback();
        return;
    }
    else if (index == 0) {
        // Update the timer with the next error data
        ErrorHandlerError ** next = (ErrorHandlerError **)min_heap_peek(&running_errors);
        if (next != NULL)
            error_handler_error_update_timer_callback((*next)->timestamp, timeouts[(*next)->group]);
    }
}

void error_handler_error_init(void (* cs_enter)(void), void (* cs_exit)(void)) {
    ring_buffer_init(&err_buf, ErrorHandlerErrorData, ERROR_HANDLER_ERROR_BUFFER_SIZE, cs_enter, cs_exit);

    for (size_t i = 0; i < instances[ERROR_HANDLER_ERROR_GROUP_POST]; ++i)
        error_handler_error_post_instances[i].group = ERROR_HANDLER_ERROR_GROUP_POST;
    for (size_t i = 0; i < instances[ERROR_HANDLER_ERROR_GROUP_OVER_CURRENT]; ++i)
        error_handler_error_over_current_instances[i].group = ERROR_HANDLER_ERROR_GROUP_OVER_CURRENT;
}
size_t error_handler_error_get_running(void) {
    return min_heap_size(&running_errors);
}
size_t error_handler_error_get_expired(void) {
    return ring_buffer_size(&expired_errors);
}
uint16_t error_handler_error_get_group_running(ErrorHandlerErrorGroup group) {
    if (group >= ERROR_HANDLER_ERROR_GROUP_COUNT)
        return 0U;
    return running_groups[group];
}
uint16_t error_handler_error_get_group_expired(ErrorHandlerErrorGroup group) {
    if (group >= ERROR_HANDLER_ERROR_GROUP_COUNT)
        return 0U;
    return expired_groups[group];
}
size_t error_handler_error_dump_running(ErrorHandlerError * out) {
    if (out == NULL)
        return 0U;

    err_buf.cs_enter();
    // Copy data
    size_t i;
    for (i = 0; i < running_errors.size; ++i)
        memcpy(&out[i], running_errors.data[i], sizeof(out[0U]));
    err_buf.cs_exit();
    return i;
}
size_t error_handler_error_dump_expired(ErrorHandlerError * out) {
    if (out == NULL)
        return 0U;

    err_buf.cs_enter();
    // Copy data
    size_t i;
    for (i = 0; i < expired_errors.size; ++i)
        memcpy(&out[i], expired_errors.data[i], sizeof(out[0U]));
    err_buf.cs_exit();
    return i;
}
size_t error_handler_error_dump_running_groups(ErrorHandlerErrorGroup * out) {
    if (out == NULL)
        return 0U;
    // Copy data
    size_t cnt = 0;
    for (size_t i = 0; i < ERROR_HANDLER_ERROR_GROUP_COUNT; ++i)
        if (running_groups[i] > 0)
            out[cnt++] = i;
    return cnt;
}
size_t error_handler_error_dump_expired_groups(ErrorHandlerErrorGroup * out) {
    if (out == NULL)
        return 0U;
    // Copy data
    size_t cnt = 0;
    for (size_t i = 0; i < ERROR_HANDLER_ERROR_GROUP_COUNT; ++i)
        if (expired_groups[i] > 0)
            out[cnt++] = i;
    return cnt;
}
void error_handler_error_set(ErrorHandlerErrorGroup group, ErrorHandlerErrorInstance instance, uint32_t timestamp) {
    if (group >= ERROR_HANDLER_ERROR_GROUP_COUNT || instance >= instances[group])
        return;

    // Push data to the buffer
    ErrorHandlerErrorData data = {
        .group = group,
        .instance = instance,
        .timestamp = timestamp,
        .op = _error_handler_error_set
    };
    if (ring_buffer_push_back(&err_buf, &data) == RING_BUFFER_OK)
        error_handler_error_routine();
}
void error_handler_error_reset(ErrorHandlerErrorGroup group, ErrorHandlerErrorInstance instance) {
    if (instance >= instances[group])
        return;

    // Push data to the buffer
    ErrorHandlerErrorData data = {
        .group = group,
        .instance = instance,
        .timestamp = 0,
        .op = _error_handler_error_reset
    };
    if (ring_buffer_push_back(&err_buf, &data) == RING_BUFFER_OK)
        error_handler_error_routine();
}
void error_handler_error_expire(void) {
    // Push data to the buffer
    ErrorHandlerErrorData data = { .op = _error_handler_error_expire };
    if (ring_buffer_push_back(&err_buf, &data) == RING_BUFFER_OK)
        error_handler_error_routine();
}
void error_handler_error_expire_immediate(ErrorHandlerErrorGroup group, ErrorHandlerErrorInstance instance) {
    if (instance >= instances[group])
        return;

    // Push data to the buffer
    ErrorHandlerErrorData data = {
        .group = group,
        .instance = instance,
        .op = _error_handler_error_expire_immediate
    };
    if (ring_buffer_push_back(&err_buf, &data) == RING_BUFFER_OK)
        error_handler_error_routine();
}
void error_handler_error_routine(void) {
    // Avoid multiple execution of the routine
    if (routine_lock)
        return;
    routine_lock = true;

    // Check if buffer is not empty
    if (ring_buffer_is_empty(&err_buf)) {
        routine_lock = false;
        return;
    }

    // Execute the right function for the error
    ErrorHandlerErrorData err;
    if (ring_buffer_pop_front(&err_buf, &err) == RING_BUFFER_OK)
        err.op(err);

    routine_lock = false;
}

__attribute__((weak)) void error_handler_error_update_timer_callback(uint32_t timestamp, uint16_t timeout) { }
__attribute__((weak)) void error_handler_error_stop_timer_callback(void) { }

