/******************************************************************************
Finite State Machine
Project: mainboard_fsm
Description: Main mainboard FSM that handles all the operations of the BMS

Generated by gv_fsm ruby gem, see https://rubygems.org/gems/gv_fsm
gv_fsm version 0.5.4
Generation date: 2024-09-01 14:36:09 +0200
Generated from: fsm.dot
The finite state machine has:
  9 states
  12 transition functions
Functions and types have been generated with prefix "fsm_"
******************************************************************************/

#ifndef FSM_H
#define FSM_H
#include <stdlib.h>
#include <stdbool.h>

/*** USER CODE BEGIN MACROS ***/
#include <stddef.h>

#include "can-bms.h"
#include "can-networks.h"
#include "mainboard-def.h"
#include "can-primary.h"

// Size of the 7-segment display animations
#define FSM_IDLE_DISPLAY_ANIMATION_SIZE (10U)
#define FSM_TS_ON_DISPLAY_ANIMATION_SIZE (6U)
#define FSM_BALANCING_DISPLAY_ANIMATION_SIZE (8U)
#define FSM_DISPLAY_ANIMATION_TICKS_PER_FRAME (100U)

/*!
 * \brief Definition of the possible events types
 *
 * \details The FSM_EVENT_TYPE_IGNORED should only be used for initialization purposes
 * and it is not counted as part of the other events
 */
typedef enum {
    FSM_EVENT_TYPE_FLASH_REQUEST,     /*!< The request for the start of a flash procedure */
    FSM_EVENT_TYPE_TS_ON,             /*!< Request for the TS on */
    FSM_EVENT_TYPE_TS_OFF,            /*!< Request for the TS off */
    FSM_EVENT_TYPE_AIRN_TIMEOUT,      /*!< The AIR- watchdog has timed out */
    FSM_EVENT_TYPE_PRECHARGE_TIMEOUT, /*!< The precharge watchdog has timed out */
    FSM_EVENT_TYPE_AIRP_TIMEOUT,      /*!< The AIR+ watchdog has timed out */
    FSM_EVENT_TYPE_BALANCING_START,   /*!< Start the balancing procedure */
    FSM_EVENT_TYPE_BALANCING_STOP,    /*!< Stop the balancing procedure */
    FSM_EVENT_TYPE_CELLBOARD_FATAL,   /*!< A cellboard has reported a fatal error */
    FSM_EVENT_TYPE_COUNT,             /*!< The number of events, not an actual event */
    FSM_EVENT_TYPE_IGNORED            /*!< Event that should be ignored */
} FsmEventType;
/*** USER CODE END MACROS ***/

// State data object
// By default set to void; override this typedef or load the proper
// header if you need
/*** USER STATE DATA TYPE BEGIN ***/
typedef void fsm_state_data;
/*** USER STATE DATA TYPE END ***/
// Event data object
// By default the struct is empty; put the data of the event inside
// the structure if you need or leave it empty
typedef struct {

    /*** USER CODE BEGIN EVENT_DATA ***/
    FsmEventType type;
    /*** USER CODE END EVENT_DATA ***/

} fsm_event_data_t;

// NOTHING SHALL BE CHANGED AFTER THIS LINE!

// List of states
typedef enum {
    FSM_STATE_INIT = 0,
    FSM_STATE_IDLE,
    FSM_STATE_FATAL,
    FSM_STATE_FLASH,
    FSM_STATE_BALANCING,
    FSM_STATE_AIRN_CHECK,
    FSM_STATE_PRECHARGE_CHECK,
    FSM_STATE_AIRP_CHECK,
    FSM_STATE_TS_ON,
    FSM_NUM_STATES,
    FSM_NO_CHANGE
} fsm_state_t;

// State human-readable names
extern const char *fsm_state_names[];

// State function and state transition prototypes
typedef fsm_state_t fsm_state_func_t(fsm_state_data *data);
typedef void transition_func_t(fsm_state_data *data);

/*** USER CODE BEGIN TYPES ***/
/*!
 * \brief Type definition for the FSM handler structure
 *
 * \attention Do not use this structure outside of this module
 */
struct FsmHandler {
    fsm_state_t fsm_state;  /*!< The current state of the FSM */
    fsm_event_data_t event; /*!< The event data of the FSM */

    fsm_event_data_t fatal_event; /*!< The event data that caused the transition to the fatal state, used for debugging purposes */

    // Canlib payloads
    union CanPrimaryMessages libcan_message_tsac_status; /*!< Libcan payload of the BMS status to send */

    enum CanPrimaryTsacstatusCellboard1status libcan_cellboard1_status; /*!< Libcan payload of the received Cellboard1 status */
    enum CanPrimaryTsacstatusCellboard2status libcan_cellboard2_status; /*!< Libcan payload of the received Cellboard2 status */
    enum CanPrimaryTsacstatusCellboard3status libcan_cellboard3_status; /*!< Libcan payload of the received Cellboard3 status */
    enum CanPrimaryTsacstatusCellboard4status libcan_cellboard4_status; /*!< Libcan payload of the received Cellboard4 status */
    enum CanPrimaryTsacstatusCellboard5status libcan_cellboard5_status; /*!< Libcan payload of the received Cellboard5 status */
    enum CanPrimaryTsacstatusCellboard6status libcan_cellboard6_status; /*!< Libcan payload of the received Cellboard6 status */
};
/*** USER CODE END TYPES ***/

// Functions to check and trigger an event
bool fsm_is_event_triggered();
void fsm_event_trigger(fsm_event_data_t *event);

// State functions

// Function to be executed in state init
// valid return states: FSM_STATE_IDLE, FSM_STATE_FATAL
fsm_state_t fsm_do_init(fsm_state_data *data);

// Function to be executed in state idle
// valid return states: FSM_NO_CHANGE, FSM_STATE_IDLE, FSM_STATE_FLASH, FSM_STATE_BALANCING, FSM_STATE_AIRN_CHECK, FSM_STATE_FATAL
fsm_state_t fsm_do_idle(fsm_state_data *data);

// Function to be executed in state fatal
// valid return states: FSM_NO_CHANGE, FSM_STATE_FLASH, FSM_STATE_FATAL
fsm_state_t fsm_do_fatal(fsm_state_data *data);

// Function to be executed in state flash
// valid return states: FSM_NO_CHANGE, FSM_STATE_IDLE, FSM_STATE_FLASH, FSM_STATE_FATAL
fsm_state_t fsm_do_flash(fsm_state_data *data);

// Function to be executed in state balancing
// valid return states: FSM_NO_CHANGE, FSM_STATE_IDLE, FSM_STATE_BALANCING, FSM_STATE_FATAL
fsm_state_t fsm_do_balancing(fsm_state_data *data);

// Function to be executed in state airn_check
// valid return states: FSM_NO_CHANGE, FSM_STATE_IDLE, FSM_STATE_AIRN_CHECK, FSM_STATE_PRECHARGE_CHECK, FSM_STATE_FATAL
fsm_state_t fsm_do_airn_check(fsm_state_data *data);

// Function to be executed in state precharge_check
// valid return states: FSM_NO_CHANGE, FSM_STATE_IDLE, FSM_STATE_PRECHARGE_CHECK, FSM_STATE_AIRP_CHECK, FSM_STATE_FATAL
fsm_state_t fsm_do_precharge_check(fsm_state_data *data);

// Function to be executed in state airp_check
// valid return states: FSM_NO_CHANGE, FSM_STATE_IDLE, FSM_STATE_AIRP_CHECK, FSM_STATE_TS_ON, FSM_STATE_FATAL
fsm_state_t fsm_do_airp_check(fsm_state_data *data);

// Function to be executed in state ts_on
// valid return states: FSM_NO_CHANGE, FSM_STATE_IDLE, FSM_STATE_TS_ON, FSM_STATE_FATAL
fsm_state_t fsm_do_ts_on(fsm_state_data *data);

// List of state functions
extern fsm_state_func_t *const fsm_state_table[FSM_NUM_STATES];

// Transition functions
void fsm_start(fsm_state_data *data);
void fsm_idle_to_fatal(fsm_state_data *data);
void fsm_start_flash_procedure(fsm_state_data *data);
void fsm_start_balancing(fsm_state_data *data);
void fsm_close_airn(fsm_state_data *data);
void fsm_handle_fatal_error(fsm_state_data *data);
void fsm_stop_flash_procedure(fsm_state_data *data);
void fsm_stop_balancing(fsm_state_data *data);
void fsm_ts_off(fsm_state_data *data);
void fsm_start_precharge(fsm_state_data *data);
void fsm_close_airp(fsm_state_data *data);
void fsm_ts_on(fsm_state_data *data);

// Table of transition functions
extern transition_func_t *const fsm_transition_table[FSM_NUM_STATES][FSM_NUM_STATES];

// state manager
fsm_state_t fsm_run_state(fsm_state_t cur_state, fsm_state_data *data);

/*** USER CODE BEGIN FUNCTIONS ***/
/*!
 * \brief Get the current status of the FSM
 *
 * \returns fsm_state_t The FSM status
 */
fsm_state_t fsm_get_status(void);

/*!
 * \brief Handle the received Cellboard 1 status libcan payload
 *
 * \param[in] status The received Cellboard status
 */
void fsm_cellboard1_state_handle(enum CanBmsTsaccellboard1fsmStatus status);

/*!
 * \brief Handle the received Cellboard 2 status libcan payload
 *
 * \param[in] status The received Cellboard status
 */
void fsm_cellboard2_state_handle(enum CanBmsTsaccellboard2fsmStatus status);

/*!
 * \brief Handle the received Cellboard 3 status libcan payload
 *
 * \param[in] status The received Cellboard status
 */
void fsm_cellboard3_state_handle(enum CanBmsTsaccellboard3fsmStatus status);

/*!
 * \brief Handle the received Cellboard 4 status libcan payload
 *
 * \param[in] status The received Cellboard status
 */
void fsm_cellboard4_state_handle(enum CanBmsTsaccellboard4fsmStatus status);

/*!
 * \brief Handle the received Cellboard 5 status libcan payload
 *
 * \param[in] status The received Cellboard status
 */
void fsm_cellboard5_state_handle(enum CanBmsTsaccellboard5fsmStatus status);

/*!
 * \brief Handle the received Cellboard 6 status libcan payload
 *
 * \param[in] status The received Cellboard status
 */
void fsm_cellboard6_state_handle(enum CanBmsTsaccellboard6fsmStatus status);

/*!
 * \brief Get a pointer to the CAN payload structure of the FSM status
 *
 * \param byte_size[out] A pointer where the size of the payload in bytes is stored (can be NULL)
 *
 * \returns A pointer to the libcan payload
 */
union CanPrimaryMessages *fsm_get_canlib_payload(size_t *byte_size);
//
/*** USER CODE END FUNCTIONS ***/

#endif
