/*!
 * \file display.h
 * \date 2024-07-04
 * \author Ettore Beltrame [ettore.beltrame@studenti.unitn.com]
 * \author Antonio Gelain [antonio.gelain2@gmail.com]
 * \author Alessandro Giustina [giustinalessandro@gmail.com]
 *
 * \brief 7-segment display handling functions
 */

#ifndef DISPLAY_H
#define DISPLAY_H

#include <stdbool.h>

#include "mainboard-def.h"
#include "mainboard-conf.h"

#include "tdsr0760.h"

/*! \brief Total number of intraframes of a display animation */
#define DISPLAY_INTRAFRAME_VERTICAL_COUNT (5U)
#define DISPLAY_INTRAFRAME_HORIZONTAL_COUNT (5U)

/*!
 * \brief Return code for the 7-segment display module function
 */
enum DisplayReturnCode {
    DISPLAY_RC_OK,                /*!< Function executed successfully */
    DISPLAY_RC_NULL_POINTER,      /*!< A NULL pointer was given to a function */
    DISPLAY_RC_INVALID_SEGMENT,   /*!< The given segment does not exist */
    DISPLAY_RC_INVALID_STATUS,    /*!< The given segment status is not valid */
    DISPLAY_RC_INVALID_CHARACTER, /*!< The given character does not exist */
    DISPLAY_RC_DRIVER_ERROR       /*!< Error caused by the display driver */
};

/*!
 * \brief Type definition for the status of a display segment
 */
enum DisplaySegmentStatus {
    DISPLAY_SEGMENT_STATUS_OFF = TDSR0760_SEGMENT_STATUS_OFF,        /*!< The segment is turned off */
    DISPLAY_SEGMENT_STATUS_ON = TDSR0760_SEGMENT_STATUS_ON,          /*!< The segment is turned on */
    DISPLAY_SEGMENT_STATUS_UNKNOWN = TDSR0760_SEGMENT_STATUS_UNKNOWN /*!< The segment status is unknown */
};

/*!
 * \brief Type definition for the display segments
 *
 * \details Each segment is labeled with its physical position in space (except the decimal point)
 */
enum DisplaySegment : int8_t {
    DISPLAY_SEGMENT_INVALID = -1,
    DISPLAY_SEGMENT_TOP = TDSR0760_SEGMENT_TOP,
    DISPLAY_SEGMENT_TOP_RIGHT = TDSR0760_SEGMENT_TOP_RIGHT,
    DISPLAY_SEGMENT_TOP_LEFT = TDSR0760_SEGMENT_TOP_LEFT,
    DISPLAY_SEGMENT_MIDDLE = TDSR0760_SEGMENT_MIDDLE,
    DISPLAY_SEGMENT_BOTTOM = TDSR0760_SEGMENT_BOTTOM,
    DISPLAY_SEGMENT_BOTTOM_RIGHT = TDSR0760_SEGMENT_BOTTOM_RIGHT,
    DISPLAY_SEGMENT_BOTTOM_LEFT = TDSR0760_SEGMENT_BOTTOM_LEFT,
    DISPLAY_SEGMENT_DECIMAL_POINT = TDSR0760_SEGMENT_DECIMAL_POINT,
    DISPLAY_SEGMENT_COUNT = TDSR0760_SEGMENT_COUNT
};

/*!
 * \brief Bit represented by each segment of the display
 *
 * \details The position of the bit for each segment is defined by the enum DisplaySegment enum
 */
enum DisplaySegmentBit {
    DISPLAY_SEGMENT_BIT_NONE = 0U,
    DISPLAY_SEGMENT_BIT_TOP = 1U << DISPLAY_SEGMENT_TOP,
    DISPLAY_SEGMENT_BIT_TOP_RIGHT = 1U << DISPLAY_SEGMENT_TOP_RIGHT,
    DISPLAY_SEGMENT_BIT_TOP_LEFT = 1U << DISPLAY_SEGMENT_TOP_LEFT,
    DISPLAY_SEGMENT_BIT_MIDDLE = 1U << DISPLAY_SEGMENT_MIDDLE,
    DISPLAY_SEGMENT_BIT_BOTTOM = 1U << DISPLAY_SEGMENT_BOTTOM,
    DISPLAY_SEGMENT_BIT_BOTTOM_RIGHT = 1U << DISPLAY_SEGMENT_BOTTOM_RIGHT,
    DISPLAY_SEGMENT_BIT_BOTTOM_LEFT = 1U << DISPLAY_SEGMENT_BOTTOM_LEFT,
    DISPLAY_SEGMENT_BIT_DECIMAL_POINT = 1U << DISPLAY_SEGMENT_DECIMAL_POINT
};

/*!
 * \brief Supported characters code for the display
 *
 * \details Each code is a bitflag where each bit represent the state of a
 * single segment of the display
 */
enum DisplayCharacterCode {
    DISPLAY_CHARACTER_CODE_0 = DISPLAY_SEGMENT_BIT_TOP | DISPLAY_SEGMENT_BIT_TOP_RIGHT |
                               DISPLAY_SEGMENT_BIT_BOTTOM_RIGHT | DISPLAY_SEGMENT_BIT_BOTTOM |
                               DISPLAY_SEGMENT_BIT_BOTTOM_LEFT | DISPLAY_SEGMENT_BIT_TOP_LEFT,
    DISPLAY_CHARACTER_CODE_1 = DISPLAY_SEGMENT_BIT_TOP_RIGHT | DISPLAY_SEGMENT_BIT_BOTTOM_RIGHT,
    DISPLAY_CHARACTER_CODE_2 = DISPLAY_SEGMENT_BIT_TOP | DISPLAY_SEGMENT_BIT_TOP_RIGHT |
                               DISPLAY_SEGMENT_BIT_MIDDLE | DISPLAY_SEGMENT_BIT_BOTTOM_LEFT |
                               DISPLAY_SEGMENT_BIT_BOTTOM,
    DISPLAY_CHARACTER_CODE_3 = DISPLAY_SEGMENT_BIT_TOP | DISPLAY_SEGMENT_BIT_TOP_RIGHT |
                               DISPLAY_SEGMENT_BIT_MIDDLE | DISPLAY_SEGMENT_BIT_BOTTOM_RIGHT |
                               DISPLAY_SEGMENT_BIT_BOTTOM,
    DISPLAY_CHARACTER_CODE_4 = DISPLAY_SEGMENT_BIT_TOP_LEFT | DISPLAY_SEGMENT_BIT_TOP_RIGHT |
                               DISPLAY_SEGMENT_BIT_MIDDLE | DISPLAY_SEGMENT_BIT_BOTTOM_RIGHT,
    DISPLAY_CHARACTER_CODE_5 = DISPLAY_SEGMENT_BIT_TOP | DISPLAY_SEGMENT_BIT_TOP_LEFT |
                               DISPLAY_SEGMENT_BIT_MIDDLE | DISPLAY_SEGMENT_BIT_BOTTOM_RIGHT |
                               DISPLAY_SEGMENT_BIT_BOTTOM,
    DISPLAY_CHARACTER_CODE_6 = DISPLAY_SEGMENT_BIT_TOP | DISPLAY_SEGMENT_BIT_TOP_LEFT |
                               DISPLAY_SEGMENT_BIT_MIDDLE | DISPLAY_SEGMENT_BIT_BOTTOM_LEFT |
                               DISPLAY_SEGMENT_BIT_BOTTOM | DISPLAY_SEGMENT_BIT_BOTTOM_RIGHT,
    DISPLAY_CHARACTER_CODE_7 = DISPLAY_SEGMENT_BIT_TOP | DISPLAY_SEGMENT_BIT_TOP_RIGHT |
                               DISPLAY_SEGMENT_BIT_BOTTOM_RIGHT,
    DISPLAY_CHARACTER_CODE_8 = DISPLAY_SEGMENT_BIT_TOP | DISPLAY_SEGMENT_BIT_TOP_RIGHT |
                               DISPLAY_SEGMENT_BIT_TOP_LEFT | DISPLAY_SEGMENT_BIT_MIDDLE |
                               DISPLAY_SEGMENT_BIT_BOTTOM_RIGHT | DISPLAY_SEGMENT_BIT_BOTTOM |
                               DISPLAY_SEGMENT_BIT_BOTTOM_LEFT,
    DISPLAY_CHARACTER_CODE_9 = DISPLAY_SEGMENT_BIT_TOP | DISPLAY_SEGMENT_BIT_TOP_RIGHT |
                               DISPLAY_SEGMENT_BIT_TOP_LEFT | DISPLAY_SEGMENT_BIT_MIDDLE |
                               DISPLAY_SEGMENT_BIT_BOTTOM_RIGHT | DISPLAY_SEGMENT_BIT_BOTTOM,
    DISPLAY_CHARACTER_CODE_A_UPCASE = DISPLAY_SEGMENT_BIT_TOP | DISPLAY_SEGMENT_BIT_TOP_RIGHT |
                                      DISPLAY_SEGMENT_BIT_TOP_LEFT | DISPLAY_SEGMENT_BIT_MIDDLE |
                                      DISPLAY_SEGMENT_BIT_BOTTOM_RIGHT | DISPLAY_SEGMENT_BIT_BOTTOM_LEFT,
    DISPLAY_CHARACTER_CODE_A_DOWNCASE = DISPLAY_SEGMENT_BIT_TOP | DISPLAY_SEGMENT_BIT_TOP_RIGHT |
                                        DISPLAY_SEGMENT_BIT_MIDDLE | DISPLAY_SEGMENT_BIT_BOTTOM_RIGHT |
                                        DISPLAY_SEGMENT_BIT_BOTTOM_LEFT | DISPLAY_SEGMENT_BIT_BOTTOM,
    DISPLAY_CHARACTER_CODE_B_DOWNCASE = DISPLAY_SEGMENT_BIT_TOP_LEFT | DISPLAY_SEGMENT_BIT_MIDDLE |
                                        DISPLAY_SEGMENT_BIT_BOTTOM_RIGHT | DISPLAY_SEGMENT_BIT_BOTTOM |
                                        DISPLAY_SEGMENT_BIT_BOTTOM_LEFT,
    DISPLAY_CHARACTER_CODE_C_UPCASE = DISPLAY_SEGMENT_BIT_TOP | DISPLAY_SEGMENT_BIT_TOP_LEFT |
                                      DISPLAY_SEGMENT_BIT_BOTTOM | DISPLAY_SEGMENT_BIT_BOTTOM_LEFT,
    DISPLAY_CHARACTER_CODE_C_DOWNCASE = DISPLAY_SEGMENT_BIT_MIDDLE | DISPLAY_SEGMENT_BIT_BOTTOM_LEFT |
                                        DISPLAY_SEGMENT_BIT_BOTTOM,
    DISPLAY_CHARACTER_CODE_D_DOWNCASE = DISPLAY_SEGMENT_BIT_TOP_RIGHT | DISPLAY_SEGMENT_BIT_MIDDLE |
                                        DISPLAY_SEGMENT_BIT_BOTTOM_RIGHT | DISPLAY_SEGMENT_BIT_BOTTOM |
                                        DISPLAY_SEGMENT_BIT_BOTTOM_LEFT,
    DISPLAY_CHARACTER_CODE_E_UPCASE = DISPLAY_SEGMENT_BIT_TOP | DISPLAY_SEGMENT_BIT_TOP_LEFT |
                                      DISPLAY_SEGMENT_BIT_MIDDLE | DISPLAY_SEGMENT_BIT_BOTTOM_LEFT |
                                      DISPLAY_SEGMENT_BIT_BOTTOM,
    DISPLAY_CHARACTER_CODE_F_UPCASE = DISPLAY_SEGMENT_BIT_TOP | DISPLAY_SEGMENT_BIT_TOP_LEFT |
                                      DISPLAY_SEGMENT_BIT_MIDDLE | DISPLAY_SEGMENT_BIT_BOTTOM_LEFT,
    DISPLAY_CHARACTER_CODE_G_UPCASE = DISPLAY_SEGMENT_BIT_TOP | DISPLAY_SEGMENT_BIT_TOP_LEFT |
                                      DISPLAY_SEGMENT_BIT_BOTTOM_LEFT | DISPLAY_SEGMENT_BIT_BOTTOM |
                                      DISPLAY_SEGMENT_BIT_BOTTOM_RIGHT,
    DISPLAY_CHARACTER_CODE_H_UPCASE = DISPLAY_SEGMENT_BIT_TOP_RIGHT | DISPLAY_SEGMENT_BIT_TOP_LEFT |
                                      DISPLAY_SEGMENT_BIT_MIDDLE | DISPLAY_SEGMENT_BIT_BOTTOM_RIGHT |
                                      DISPLAY_SEGMENT_BIT_BOTTOM_LEFT,
    DISPLAY_CHARACTER_CODE_H_DOWNCASE = DISPLAY_SEGMENT_BIT_TOP_LEFT | DISPLAY_SEGMENT_BIT_MIDDLE |
                                        DISPLAY_SEGMENT_BIT_BOTTOM_RIGHT | DISPLAY_SEGMENT_BIT_BOTTOM_LEFT,
    DISPLAY_CHARACTER_CODE_I_UPCASE = DISPLAY_SEGMENT_BIT_TOP_LEFT | DISPLAY_SEGMENT_BIT_BOTTOM_LEFT,
    DISPLAY_CHARACTER_CODE_I_DOWNCASE = DISPLAY_SEGMENT_BIT_TOP | DISPLAY_SEGMENT_BIT_BOTTOM_LEFT | DISPLAY_SEGMENT_BIT_BOTTOM,
    DISPLAY_CHARACTER_CODE_J_UPCASE = DISPLAY_SEGMENT_BIT_TOP_RIGHT | DISPLAY_SEGMENT_BIT_BOTTOM_RIGHT |
                                      DISPLAY_SEGMENT_BIT_BOTTOM_LEFT | DISPLAY_SEGMENT_BIT_BOTTOM,
    DISPLAY_CHARACTER_CODE_J_DOWNCASE = DISPLAY_SEGMENT_BIT_TOP | DISPLAY_SEGMENT_BIT_BOTTOM_RIGHT |
                                        DISPLAY_SEGMENT_BIT_BOTTOM,
    DISPLAY_CHARACTER_CODE_K_UPCASE = DISPLAY_SEGMENT_BIT_TOP | DISPLAY_SEGMENT_BIT_TOP_LEFT |
                                      DISPLAY_SEGMENT_BIT_MIDDLE | DISPLAY_SEGMENT_BIT_BOTTOM_LEFT |
                                      DISPLAY_SEGMENT_BIT_BOTTOM_RIGHT,
    DISPLAY_CHARACTER_CODE_L_UPCASE = DISPLAY_SEGMENT_BIT_TOP_LEFT | DISPLAY_SEGMENT_BIT_BOTTOM_LEFT |
                                      DISPLAY_SEGMENT_BIT_BOTTOM,
    DISPLAY_CHARACTER_CODE_M_UPCASE = DISPLAY_SEGMENT_BIT_TOP | DISPLAY_SEGMENT_BIT_MIDDLE |
                                      DISPLAY_SEGMENT_BIT_BOTTOM_LEFT | DISPLAY_SEGMENT_BIT_BOTTOM_RIGHT,
    DISPLAY_CHARACTER_CODE_N_DOWNCASE = DISPLAY_SEGMENT_BIT_MIDDLE | DISPLAY_SEGMENT_BIT_BOTTOM_LEFT |
                                        DISPLAY_SEGMENT_BIT_BOTTOM_RIGHT,
    DISPLAY_CHARACTER_CODE_O_DOWNCASE = DISPLAY_SEGMENT_BIT_MIDDLE | DISPLAY_SEGMENT_BIT_BOTTOM_LEFT |
                                        DISPLAY_SEGMENT_BIT_BOTTOM_RIGHT | DISPLAY_SEGMENT_BIT_BOTTOM,
    DISPLAY_CHARACTER_CODE_P_UPCASE = DISPLAY_SEGMENT_BIT_TOP | DISPLAY_SEGMENT_BIT_TOP_RIGHT |
                                      DISPLAY_SEGMENT_BIT_TOP_LEFT | DISPLAY_SEGMENT_BIT_MIDDLE |
                                      DISPLAY_SEGMENT_BIT_BOTTOM_LEFT,
    DISPLAY_CHARACTER_CODE_Q_DOWNCASE = DISPLAY_SEGMENT_BIT_TOP | DISPLAY_SEGMENT_BIT_TOP_RIGHT |
                                        DISPLAY_SEGMENT_BIT_TOP_LEFT | DISPLAY_SEGMENT_BIT_MIDDLE |
                                        DISPLAY_SEGMENT_BIT_BOTTOM_RIGHT,
    DISPLAY_CHARACTER_CODE_R_DOWNCASE = DISPLAY_SEGMENT_BIT_MIDDLE | DISPLAY_SEGMENT_BIT_BOTTOM_LEFT,
    DISPLAY_CHARACTER_CODE_S_UPCASE = DISPLAY_SEGMENT_BIT_TOP | DISPLAY_SEGMENT_BIT_TOP_LEFT |
                                      DISPLAY_SEGMENT_BIT_BOTTOM_RIGHT | DISPLAY_SEGMENT_BIT_BOTTOM,
    DISPLAY_CHARACTER_CODE_T_DOWNCASE = DISPLAY_SEGMENT_BIT_TOP_LEFT | DISPLAY_SEGMENT_BIT_MIDDLE |
                                        DISPLAY_SEGMENT_BIT_BOTTOM_LEFT | DISPLAY_SEGMENT_BIT_BOTTOM,
    DISPLAY_CHARACTER_CODE_U_UPCASE = DISPLAY_SEGMENT_BIT_TOP_LEFT | DISPLAY_SEGMENT_BIT_TOP_RIGHT |
                                      DISPLAY_SEGMENT_BIT_BOTTOM_LEFT | DISPLAY_SEGMENT_BIT_BOTTOM_RIGHT |
                                      DISPLAY_SEGMENT_BIT_BOTTOM,
    DISPLAY_CHARACTER_CODE_U_DOWNCASE = DISPLAY_SEGMENT_BIT_BOTTOM_LEFT | DISPLAY_SEGMENT_BIT_BOTTOM_RIGHT |
                                        DISPLAY_SEGMENT_BIT_BOTTOM,
    DISPLAY_CHARACTER_CODE_V_UPCASE = DISPLAY_SEGMENT_BIT_TOP_LEFT | DISPLAY_SEGMENT_BIT_TOP_RIGHT |
                                      DISPLAY_SEGMENT_BIT_BOTTOM,
    DISPLAY_CHARACTER_CODE_W_UPCASE = DISPLAY_SEGMENT_BIT_TOP_LEFT | DISPLAY_SEGMENT_BIT_TOP_RIGHT |
                                      DISPLAY_SEGMENT_BIT_MIDDLE | DISPLAY_SEGMENT_BIT_BOTTOM,
    DISPLAY_CHARACTER_CODE_X_UPCASE = DISPLAY_SEGMENT_BIT_TOP_LEFT | DISPLAY_SEGMENT_BIT_TOP_RIGHT |
                                      DISPLAY_SEGMENT_BIT_BOTTOM_LEFT | DISPLAY_SEGMENT_BIT_BOTTOM_RIGHT,
    DISPLAY_CHARACTER_CODE_X_DOWNCASE = DISPLAY_SEGMENT_BIT_BOTTOM_LEFT | DISPLAY_SEGMENT_BIT_BOTTOM_RIGHT,
    DISPLAY_CHARACTER_CODE_Y_DOWNCASE = DISPLAY_SEGMENT_BIT_TOP_RIGHT | DISPLAY_SEGMENT_BIT_TOP_LEFT |
                                        DISPLAY_SEGMENT_BIT_MIDDLE | DISPLAY_SEGMENT_BIT_BOTTOM_RIGHT |
                                        DISPLAY_SEGMENT_BIT_BOTTOM,
    DISPLAY_CHARACTER_CODE_Z_UPCASE = DISPLAY_SEGMENT_BIT_TOP | DISPLAY_SEGMENT_BIT_TOP_LEFT |
                                      DISPLAY_SEGMENT_BIT_BOTTOM_RIGHT | DISPLAY_SEGMENT_BIT_BOTTOM,
    DISPLAY_CHARACTER_CODE_SPACE = DISPLAY_SEGMENT_BIT_NONE,
    DISPLAY_CHARACTER_CODE_DOT = DISPLAY_SEGMENT_BIT_DECIMAL_POINT,
    DISPLAY_CHARACTER_CODE_HYPEN = DISPLAY_SEGMENT_BIT_MIDDLE,
    DISPLAY_CHARACTER_CODE_UNDERSCORE = DISPLAY_SEGMENT_BIT_BOTTOM
};

/*!
 * \brief Type definition for a function callback that should set the state of the display segment
 *
 * \param segment The segment to select
 * \param state The new state to set
 */
typedef void (*display_segment_set_state_callback)(const enum DisplaySegment segment, const enum DisplaySegmentStatus state);

/*!
 * \brief Type definition for a function callback that should toggle the state of the display segment
 *
 * \param segment The segment to select
 */
typedef void (*display_segment_toggle_state_callback)(const enum DisplaySegment segment);

/*!
 * \brief 7-segment display handler structure
 * 
 * \attention Do not use this struct outside this module
 */
struct DisplayHandler {
    display_segment_set_state_callback set;       /*!< Pointer to the function callback that should set the state of a selected segment */
    display_segment_toggle_state_callback toggle; /*!< Pointer to the function callback that should toggle the state of a selected segment */

    Tdsr0760Handler tdsr0760; /*!< Handler structure of the 7-segment display driver */
};

#endif // DISPLAY_H
